statuspage_app/statuspage/incidents/api/urls.py
from statuspage.api.routers import StatusPageRouter
from . import views


router = StatusPageRouter()
router.APIRootView = views.IncidentsRootView

router.register('incidents', views.IncidentViewSet)
router.register('incident-updates', views.IncidentUpdateViewSet)
router.register('incident-templates', views.IncidentTemplateViewSet)

app_name = 'incidents-api'
urlpatterns = router.urls

statuspage_app/statuspage/incidents/urls.py
from django.urls import path, include

from utilities.urls import get_model_urls
from . import views # noqa Required for registration

app_name = 'incidents'
urlpatterns = [
    path('', include(get_model_urls('incidents', 'incident'))),
    path('update/', include(get_model_urls('incidents', 'incidentupdate'))),
    path('template/', include(get_model_urls('incidents', 'incidenttemplate'))),
]

statuspage_app/statuspage/statuspage/urls.py
from django.conf import settings
from django.views.static import serve

from extras.plugins.urls import plugin_patterns, plugin_api_patterns, plugin_admin_patterns
from .admin import admin_site
from django.urls import path, include, re_path
from statuspage.views import HomeView, DashboardHomeView, SubscriberVerifyView, SubscriberManageView, \
    SubscriberUnsubscribeView, SubscriberSubscribeView, SubscriberRequestManagementKeyView, \
    SubscriberManageWebhookListView, SubscriberManageWebhookCreateView, SubscriberManageWebhookDeleteView, \
    SubscriberManageWebhookEditView
from users.views import LoginView, LogoutView
from statuspage.api.views import APIRootView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

openapi_info = openapi.Info(
    title="Status-Page API",
    default_version='v1',
    description="API to access Status-Page",
    terms_of_service="https://github.com/status-page/status-page",
    license=openapi.License(name="Apache 2.0 License"),
)

schema_view = get_schema_view(
    openapi_info,
    validators=['flex', 'ssv'],
    public=True,
    permission_classes=()
)

_patterns = [
    # Base Views
    path('', HomeView.as_view(), name='home'),

    path('subscribers/subscribe', SubscriberSubscribeView.as_view(), name='subscriber_subscribe'),
    path('subscribers/reqeust-management-key', SubscriberRequestManagementKeyView.as_view(), name='subscriber_management_key'),
    path('subscribers/<str:management_key>/verify', SubscriberVerifyView.as_view(), name='subscriber_verify'),
    path('subscribers/<str:management_key>/manage', SubscriberManageView.as_view(), name='subscriber_manage'),
    path('subscribers/<str:management_key>/manage/webhooks', SubscriberManageWebhookListView.as_view(), name='subscriber_manage_webhook_list'),
    path('subscribers/<str:management_key>/manage/webhooks/create', SubscriberManageWebhookCreateView.as_view(), name='subscriber_manage_webhook_create'),
    path('subscribers/<str:management_key>/manage/webhooks/<int:webhook>/edit', SubscriberManageWebhookEditView.as_view(), name='subscriber_manage_webhook_edit'),
    path('subscribers/<str:management_key>/manage/webhooks/<int:webhook>/delete', SubscriberManageWebhookDeleteView.as_view(), name='subscriber_manage_webhook_delete'),
    path('subscribers/<str:management_key>/unsubscribe', SubscriberUnsubscribeView.as_view(), name='subscriber_unsubscribe'),

    path('dashboard/', DashboardHomeView.as_view(), name='dashboard'),
    path('dashboard/login/', LoginView.as_view(), name='login'),
    path('dashboard/logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path('dashboard/components/', include('components.urls')),
    path('dashboard/extras/', include('extras.urls')),
    path('dashboard/incidents/', include('incidents.urls')),
    path('dashboard/maintenances/', include('maintenances.urls')),
    path('dashboard/metrics/', include('metrics.urls')),
    path('dashboard/subscribers/', include('subscribers.urls')),
    path('dashboard/user/', include('users.urls')),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/components/', include('components.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/incidents/', include('incidents.api.urls')),
    path('api/maintenances/', include('maintenances.api.urls')),
    path('api/metrics/', include('metrics.api.urls')),
    path('api/subscribers/', include('subscribers.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=86400), name='api_docs'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=86400), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(cache_timeout=86400),
            name='schema_swagger'),

    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),

    # Admin
    path('admin/background-tasks/', include('django_rq.urls')),
    path('admin/plugins/', include(plugin_admin_patterns)),
    path('admin/', admin_site.urls),

    path('__reload__/', include('django_browser_reload.urls')),
]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

statuspage_app/statuspage/users/urls.py
from django.urls import path, include

from utilities.urls import get_model_urls
from . import views

app_name = 'users'
urlpatterns = [
    # User
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('preferences/', views.UserConfigView.as_view(), name='preferences'),
    path('password/', views.ChangePasswordView.as_view(), name='change_password'),

    # API Tokens
    path('api-tokens/', include(get_model_urls('users', 'token'))),

    # Two-Factor devices
    path('twofactor/', views.TwoFactorListView.as_view(), name='device_list'),
    path('twofactor/add/', views.TwoFactorEditView.as_view(), name='device_add'),
    path('twofactor/<int:pk>/backup-codes/', views.TwoFactorBackupCodesListView.as_view(), name='device_backup_codes'),
    path('twofactor/<int:pk>/qr-code/', views.TwoFactorQRCodeListView.as_view(), name='device_qr_code'),
    path('twofactor/<int:pk>/edit/', views.TwoFactorEditView.as_view(), name='device_edit'),
    path('twofactor/<int:pk>/delete/', views.TwoFactorDeleteView.as_view(), name='device_delete'),
]

statuspage_app/statuspage/incidents/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

from incidents.choices import *
from components.models import Component
from utilities.models import IncidentMaintenanceModel, IncidentMaintenanceUpdateModel


class Incident(IncidentMaintenanceModel):
    status = models.CharField(
        max_length=255,
        choices=IncidentStatusChoices,
        default=IncidentStatusChoices.INVESTIGATING,
    )
    impact = models.CharField(
        max_length=255,
        choices=IncidentImpactChoices,
        default=IncidentImpactChoices.NONE,
    )
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        related_name='incidents',
        blank=True,
        null=True
    )
    components = models.ManyToManyField(
        to=Component,
        related_name='incidents',
        blank=True,
    )
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('incidents:incident', args=[self.pk])

    def get_impact_color(self):
        (color, _, __) = IncidentImpactChoices.colors.get(self.impact)
        return color

    def get_impact_border_color(self):
        (_, color, __) = IncidentImpactChoices.colors.get(self.impact)
        return color

    def get_impact_text_color(self):
        (_, __, color) = IncidentImpactChoices.colors.get(self.impact)
        return color


class IncidentUpdate(IncidentMaintenanceUpdateModel):
    incident = models.ForeignKey(
        to=Incident,
        on_delete=models.CASCADE,
        related_name='updates',
    )
    status = models.CharField(
        max_length=255,
        choices=IncidentStatusChoices,
    )
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        related_name='incident_updates',
        blank=True,
        null=True
    )
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.incident.title} - Update {self.pk}'

    def get_absolute_url(self):
        return reverse('incidents:incidentupdate', args=[self.pk])


class IncidentTemplate(IncidentMaintenanceModel):
    template_name = models.CharField(
        max_length=255,
    )
    status = models.CharField(
        max_length=255,
        choices=IncidentStatusChoices,
        default=IncidentStatusChoices.INVESTIGATING,
    )
    impact = models.CharField(
        max_length=255,
        choices=IncidentImpactChoices,
        default=IncidentImpactChoices.NONE,
    )
    components = models.ManyToManyField(
        to=Component,
        related_name='+',
        blank=True,
    )
    update_component_status = models.BooleanField(
        default=False,
    )
    text = models.CharField(
        max_length=65536,
    )

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.template_name

    def get_absolute_url(self):
        return reverse('incidents:incidenttemplate', args=[self.pk])

    def get_impact_color(self):
        (color, _, __) = IncidentImpactChoices.colors.get(self.impact)
        return color

    def get_impact_border_color(self):
        (_, color, __) = IncidentImpactChoices.colors.get(self.impact)
        return color

    def get_impact_text_color(self):
        (_, __, color) = IncidentImpactChoices.colors.get(self.impact)
        return color

statuspage_app/statuspage/incidents/forms/bulk.py
from statuspage.forms import StatusPageModelBulkEditForm
from utilities.forms import StaticSelect, StaticSelectMultiple, add_blank_choice, BulkEditNullBooleanSelect
from .. import choices
from ..models import Incident, IncidentUpdate, IncidentTemplate
from django import forms
from components.models import Component

__all__ = (
    'IncidentBulkEditForm',
    'IncidentUpdateBulkEditForm',
    'IncidentTemplateBulkEditForm',
)


class IncidentBulkEditForm(StatusPageModelBulkEditForm):
    status = forms.ChoiceField(
        choices=add_blank_choice(choices.IncidentStatusChoices),
        required=False,
        widget=StaticSelect(),
    )
    impact = forms.ChoiceField(
        choices=add_blank_choice(choices.IncidentImpactChoices),
        required=False,
        widget=StaticSelect(),
    )
    visibility = forms.NullBooleanField(
        required=False,
        widget=BulkEditNullBooleanSelect,
        label='Visible',
    )
    components = forms.ModelMultipleChoiceField(
        queryset=Component.objects.all(),
        required=False,
        widget=StaticSelectMultiple(),
    )

    model = Incident
    fieldsets = (
        ('Incident', ('status', 'impact', 'visibility', 'components')),
    )
    nullable_fields = ('components',)


class IncidentUpdateBulkEditForm(StatusPageModelBulkEditForm):
    new_status = forms.NullBooleanField(
        required=False,
        widget=BulkEditNullBooleanSelect,
        label='New Status',
    )
    status = forms.ChoiceField(
        choices=add_blank_choice(choices.IncidentStatusChoices),
        required=False,
        widget=StaticSelect(),
    )

    model = IncidentUpdate
    fieldsets = (
        ('Incident Update', ('new_status', 'status',)),
    )


class IncidentTemplateBulkEditForm(StatusPageModelBulkEditForm):
    status = forms.ChoiceField(
        choices=add_blank_choice(choices.IncidentStatusChoices),
        required=False,
        widget=StaticSelect(),
    )
    impact = forms.ChoiceField(
        choices=add_blank_choice(choices.IncidentImpactChoices),
        required=False,
        widget=StaticSelect(),
    )
    visibility = forms.NullBooleanField(
        required=False,
        widget=BulkEditNullBooleanSelect,
        label='Visible',
    )
    components = forms.ModelMultipleChoiceField(
        queryset=Component.objects.all(),
        required=False,
        widget=StaticSelectMultiple(),
    )
    update_component_status = forms.NullBooleanField(
        required=False,
        widget=BulkEditNullBooleanSelect,
        label='Update Component Status',
    )

    model = IncidentTemplate
    fieldsets = (
        ('Incident Template', ('status', 'impact', 'visibility', 'components', 'update_component_status')),
    )
    nullable_fields = ('components',)

statuspage_app/statuspage/incidents/forms/filtersets.py
from django import forms
from django.contrib.auth.models import User

from components.models import Component
from incidents.models import Incident, IncidentTemplate
from incidents.choices import IncidentStatusChoices, IncidentImpactChoices
from utilities.forms import FilterForm, StaticSelect, add_blank_choice, \
    BOOLEAN_WITH_BLANK_CHOICES, StaticSelectMultiple

__all__ = (
    'IncidentFilterForm',
    'IncidentTemplateFilterForm',
)


class IncidentFilterForm(FilterForm):
    model = Incident
    fieldsets = (
        (None, ('q',)),
        ('Incident', ('title', 'status', 'impact', 'visibility', 'user_id', 'component_id')),
    )
    title = forms.CharField(
        required=False,
    )
    status = forms.ChoiceField(
        required=False,
        choices=add_blank_choice(IncidentStatusChoices),
        widget=StaticSelect(),
    )
    impact = forms.ChoiceField(
        required=False,
        choices=add_blank_choice(IncidentImpactChoices),
        widget=StaticSelect(),
    )
    visibility = forms.NullBooleanField(
        required=False,
        widget=StaticSelect(
            choices=BOOLEAN_WITH_BLANK_CHOICES,
        ),
    )
    user_id = forms.ModelChoiceField(
        required=False,
        queryset=User.objects.all(),
        widget=StaticSelect(),
        label='User',
    )
    component_id = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Component.objects.all(),
        widget=StaticSelectMultiple(),
        label='Components',
    )


class IncidentTemplateFilterForm(FilterForm):
    model = IncidentTemplate
    fieldsets = (
        (None, ('q',)),
        ('Incident Template', ('template_name', 'title', 'status', 'impact', 'visibility', 'component_id',
                               'update_component_status')),
    )
    template_name = forms.CharField(
        required=False,
    )
    title = forms.CharField(
        required=False,
    )
    status = forms.ChoiceField(
        required=False,
        choices=add_blank_choice(IncidentStatusChoices),
        widget=StaticSelect(),
    )
    impact = forms.ChoiceField(
        required=False,
        choices=add_blank_choice(IncidentImpactChoices),
        widget=StaticSelect(),
    )
    visibility = forms.NullBooleanField(
        required=False,
        widget=StaticSelect(
            choices=BOOLEAN_WITH_BLANK_CHOICES,
        ),
    )
    component_id = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Component.objects.all(),
        widget=StaticSelectMultiple(),
        label='Components',
    )
    update_component_status = forms.NullBooleanField(
        required=False,
        widget=StaticSelect(
            choices=BOOLEAN_WITH_BLANK_CHOICES,
        ),
    )

statuspage_app/statuspage/incidents/api/views.py
from rest_framework.routers import APIRootView
from rest_framework.viewsets import ModelViewSet

from incidents.api import serializers
from incidents import filtersets
from incidents.models import Incident, IncidentUpdate, IncidentTemplate


class IncidentsRootView(APIRootView):
    """
    Components API root view
    """
    def get_view_name(self):
        return 'Incidents'


class IncidentViewSet(ModelViewSet):
    queryset = Incident.objects.all()
    serializer_class = serializers.IncidentSerializer
    filterset_class = filtersets.IncidentFilterSet


class IncidentUpdateViewSet(ModelViewSet):
    queryset = IncidentUpdate.objects.all()
    serializer_class = serializers.IncidentUpdateSerializer
    filterset_class = filtersets.IncidentUpdateFilterSet


class IncidentTemplateViewSet(ModelViewSet):
    queryset = IncidentTemplate.objects.all()
    serializer_class = serializers.IncidentTemplateSerializer
    filterset_class = filtersets.IncidentTemplateFilterSet

statuspage_app/statuspage/templates/incidents/incident.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}

{% block page_left %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Incident</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">Title</th>
            <td>{{ object.title }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Visible</th>
            <td>{% checkmark object.visibility %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Status</th>
            <td>{{ object.get_status_display }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Impact</th>
            <td>{% badge object.get_impact_display bg_color=object.get_impact_color %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">User</th>
            <td>
              {% if object.user.get_full_name %}
                {{ object.user.get_full_name }} ({{ object.user.username }})
              {% else %}
                {{ object.user.username }}
              {% endif %}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block page_right %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Affected Components</div>
    <div class="px-4 flex flex-col w-1/2 divide-y divide-gray-200 dark:divide-gray-700">
      {% for component in object.components.all %}
        <div class="grid grid-cols-2 gap-2 py-1">
          <div>{{ component|linkify }}</div>
          <div>{% badge component.get_status_display component.get_status_color %}</div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

statuspage_app/statuspage/templates/incidents/incident_edit.html
{% extends 'base/dashboard.html' %}
{% load form_helpers %}
{% load helpers %}

{% block title %}
  {% if object.pk %}Editing {{ object|meta:"verbose_name" }} {{ object }}{% else %}Add a new {{ object|meta:"verbose_name" }}{% endif %}
{% endblock title %}

{% block controls %}
  <form method="get" class="flex flex-row items-end space-x-1" id="template-selector">
    {% render_form template_form %}
    <button class="bg-green-500 hover:bg-green-400 text-white px-2 py-2 rounded-md font-medium" type="submit">
      Select Template
    </button>
  </form>
{% endblock controls %}

{% block dashboard_content %}
<div class="bg-zinc-200 dark:bg-zinc-800 shadow px-4 py-2 rounded-md">
  <form action="" method="post" enctype="multipart/form-data" class="form-object-edit mt-5">
    {% csrf_token %}

    {% block form %}
      {% if form.fieldsets %}

        {# Render hidden fields #}
        {% for field in form.hidden_fields %}
          {{ field }}
        {% endfor %}

        {# Render grouped fields according to Form #}
        <div class="space-y-4 divide-y dark:divide-gray-500">
          {% for group, fields in form.fieldsets %}
            <div class="">
              {% if group %}
                <div class="mb-4">
                  <span class="text-2xl">{{ group }}</span>
                </div>
              {% endif %}
              <div class="space-y-4">
                {% for name in fields %}
                  {% with field=form|getfield:name %}
                    {% if not field.field.widget.is_hidden %}
                      {% render_field field %}
                    {% endif %}
                  {% endwith %}
                {% endfor %}
              </div>
            </div>
          {% endfor %}
        </div>

      {% else %}
        {# Render all fields in a single group #}
        <div class="">
          {% render_form form %}
        </div>
      {% endif %}

    {% endblock form %}

    <div class="my-3 flex flex-row items-center justify-end space-x-2">
      {% block buttons %}
        {% if object.pk %}
          <button type="submit" name="_update" class="bg-green-500 hover:bg-green-400 text-white px-2 py-1 rounded-md font-medium h-8 flex items-center">
            Save
          </button>
        {% else %}
          <button type="submit" name="_create" class="bg-green-500 hover:bg-green-400 text-white px-2 py-1 rounded-md font-medium h-8 flex items-center">
            Create
          </button>
          <button type="submit" name="_addanother" class="border border-green-500 hover:bg-green-500 hover:text-white text-green-500 px-2 py-1 rounded-md font-medium h-8 flex items-center">
            Create & Add Another
          </button>
        {% endif %}
        <a class="border border-gray-500 hover:bg-gray-500 hover:text-white text-gray-500 px-2 py-1 rounded-md font-medium h-8 flex items-center" href="{{ return_url }}">Cancel</a>
      {% endblock buttons %}
    </div>
  </form>
</div>
{% endblock %}

statuspage_app/statuspage/templates/incidents/incidenttemplate.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}

{% block extra_controls %}
  {% if perms.incidents.add_incidents %}
    <a href="{% url 'incidents:incident_add' %}?template={{ object.pk }}" class="bg-green-500 hover:bg-green-400 text-white px-2 py-2 rounded-md font-medium" type="button">
      <i class="mdi mdi-plus-thick"></i> Create Incident
    </a>
  {% endif %}
{% endblock %}

{% block page_left %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Incident Template</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">Template Name</th>
            <td>{{ object.template_name }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Title</th>
            <td>{{ object.title }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Visible</th>
            <td>{% checkmark object.visibility %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Status</th>
            <td>{{ object.get_status_display }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Impact</th>
            <td>{% badge object.get_impact_display bg_color=object.get_impact_color %}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block page_right %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Affected Components</div>
    <div class="px-4 flex flex-col w-1/2 divide-y divide-gray-200 dark:divide-gray-700">
      {% for component in object.components.all %}
        <div class="grid grid-cols-2 gap-2 py-1">
          <div>{{ component|linkify }}</div>
          <div>{% badge component.get_status_display component.get_status_color %}</div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block page_full %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Text</div>
    <div class="px-4">
      {{ object.text|markdown }}
    </div>
  </div>
{% endblock %}

statuspage_app/statuspage/templates/incidents/incidentupdate.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}

{% block page_full %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Incident Update</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">New Status</th>
            <td>{% checkmark object.new_status %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Status</th>
            <td>{{ object.get_status_display }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">User</th>
            <td>
              {% if object.user.get_full_name %}
                {{ object.user.get_full_name }} ({{ object.user.username }})
              {% else %}
                {{ object.user.username }}
              {% endif %}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div>
      <div class="border-b border-zinc-500"></div>
      <div>Update Text:</div>
      <div>
        {{ object.text|markdown }}
      </div>
    </div>
  </div>
{% endblock %}