statuspage_app/statuspage/components/api/urls.py
from statuspage.api.routers import StatusPageRouter
from . import views


router = StatusPageRouter()
router.APIRootView = views.ComponentsRootView

router.register('components', views.ComponentViewSet)
router.register('component-groups', views.ComponentGroupViewSet)

app_name = 'components-api'
urlpatterns = router.urls

statuspage_app/statuspage/components/urls.py
from django.urls import path, include

from utilities.urls import get_model_urls

from . import views # noqa Required for registration

app_name = 'components'
urlpatterns = [
    path('', include(get_model_urls('components', 'component'))),
    path('groups/', include(get_model_urls('components', 'componentgroup'))),
]

statuspage_app/statuspage/statuspage/urls.py
from django.conf import settings
from django.views.static import serve

from extras.plugins.urls import plugin_patterns, plugin_api_patterns, plugin_admin_patterns
from .admin import admin_site
from django.urls import path, include, re_path
from statuspage.views import HomeView, DashboardHomeView, SubscriberVerifyView, SubscriberManageView, \
    SubscriberUnsubscribeView, SubscriberSubscribeView, SubscriberRequestManagementKeyView, \
    SubscriberManageWebhookListView, SubscriberManageWebhookCreateView, SubscriberManageWebhookDeleteView, \
    SubscriberManageWebhookEditView
from users.views import LoginView, LogoutView
from statuspage.api.views import APIRootView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

openapi_info = openapi.Info(
    title="Status-Page API",
    default_version='v1',
    description="API to access Status-Page",
    terms_of_service="https://github.com/status-page/status-page",
    license=openapi.License(name="Apache 2.0 License"),
)

schema_view = get_schema_view(
    openapi_info,
    validators=['flex', 'ssv'],
    public=True,
    permission_classes=()
)

_patterns = [
    # Base Views
    path('', HomeView.as_view(), name='home'),

    path('subscribers/subscribe', SubscriberSubscribeView.as_view(), name='subscriber_subscribe'),
    path('subscribers/reqeust-management-key', SubscriberRequestManagementKeyView.as_view(), name='subscriber_management_key'),
    path('subscribers/<str:management_key>/verify', SubscriberVerifyView.as_view(), name='subscriber_verify'),
    path('subscribers/<str:management_key>/manage', SubscriberManageView.as_view(), name='subscriber_manage'),
    path('subscribers/<str:management_key>/manage/webhooks', SubscriberManageWebhookListView.as_view(), name='subscriber_manage_webhook_list'),
    path('subscribers/<str:management_key>/manage/webhooks/create', SubscriberManageWebhookCreateView.as_view(), name='subscriber_manage_webhook_create'),
    path('subscribers/<str:management_key>/manage/webhooks/<int:webhook>/edit', SubscriberManageWebhookEditView.as_view(), name='subscriber_manage_webhook_edit'),
    path('subscribers/<str:management_key>/manage/webhooks/<int:webhook>/delete', SubscriberManageWebhookDeleteView.as_view(), name='subscriber_manage_webhook_delete'),
    path('subscribers/<str:management_key>/unsubscribe', SubscriberUnsubscribeView.as_view(), name='subscriber_unsubscribe'),

    path('dashboard/', DashboardHomeView.as_view(), name='dashboard'),
    path('dashboard/login/', LoginView.as_view(), name='login'),
    path('dashboard/logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path('dashboard/components/', include('components.urls')),
    path('dashboard/extras/', include('extras.urls')),
    path('dashboard/incidents/', include('incidents.urls')),
    path('dashboard/maintenances/', include('maintenances.urls')),
    path('dashboard/metrics/', include('metrics.urls')),
    path('dashboard/subscribers/', include('subscribers.urls')),
    path('dashboard/user/', include('users.urls')),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/components/', include('components.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/incidents/', include('incidents.api.urls')),
    path('api/maintenances/', include('maintenances.api.urls')),
    path('api/metrics/', include('metrics.api.urls')),
    path('api/subscribers/', include('subscribers.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=86400), name='api_docs'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=86400), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(cache_timeout=86400),
            name='schema_swagger'),

    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),

    # Admin
    path('admin/background-tasks/', include('django_rq.urls')),
    path('admin/plugins/', include(plugin_admin_patterns)),
    path('admin/', admin_site.urls),

    path('__reload__/', include('django_browser_reload.urls')),
]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

statuspage_app/statuspage/users/urls.py
from django.urls import path, include

from utilities.urls import get_model_urls
from . import views

app_name = 'users'
urlpatterns = [
    # User
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('preferences/', views.UserConfigView.as_view(), name='preferences'),
    path('password/', views.ChangePasswordView.as_view(), name='change_password'),

    # API Tokens
    path('api-tokens/', include(get_model_urls('users', 'token'))),

    # Two-Factor devices
    path('twofactor/', views.TwoFactorListView.as_view(), name='device_list'),
    path('twofactor/add/', views.TwoFactorEditView.as_view(), name='device_add'),
    path('twofactor/<int:pk>/backup-codes/', views.TwoFactorBackupCodesListView.as_view(), name='device_backup_codes'),
    path('twofactor/<int:pk>/qr-code/', views.TwoFactorQRCodeListView.as_view(), name='device_qr_code'),
    path('twofactor/<int:pk>/edit/', views.TwoFactorEditView.as_view(), name='device_edit'),
    path('twofactor/<int:pk>/delete/', views.TwoFactorDeleteView.as_view(), name='device_delete'),
]

statuspage_app/statuspage/components/models.py
from django.db import models
from statuspage.models import StatusPageModel
from django.urls import reverse
from components.choices import *


class ComponentGroup(StatusPageModel):
    name = models.CharField(
        max_length=255,
    )
    description = models.CharField(
        max_length=255,
        blank=True,
    )
    visibility = models.BooleanField(
        default=False,
    )
    order = models.IntegerField(
        default=1,
    )
    collapse = models.CharField(
        max_length=255,
        choices=ComponentGroupCollapseChoices,
        default='expand_issue'
    )

    class Meta:
        ordering = ['order', 'pk']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('components:componentgroup', args=[self.pk])

    @property
    def should_expand(self):
        if self.collapse == ComponentGroupCollapseChoices.ALWAYS:
            return 'true'
        for component in self.components.all():
            if component.status != ComponentStatusChoices.OPERATIONAL:
                return 'true'
        return 'false'


class Component(StatusPageModel):
    name = models.CharField(
        max_length=255,
    )
    link = models.URLField(
        blank=True,
    )
    description = models.CharField(
        max_length=255,
        blank=True,
    )
    component_group = models.ForeignKey(
        to=ComponentGroup,
        on_delete=models.CASCADE,
        related_name='components',
        blank=True,
        null=True,
    )
    show_historic_incidents = models.BooleanField(
        default=True,
    )
    visibility = models.BooleanField(
        default=False,
    )
    status = models.CharField(
        max_length=255,
        choices=ComponentStatusChoices,
        default='operational',
    )
    order = models.IntegerField(
        default=1,
    )

    class Meta:
        ordering = ['component_group', 'order', 'pk']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('components:component', args=[self.pk])

    def get_status_color(self):
        (color, _) = ComponentStatusChoices.colors.get(self.status)
        return color

    def get_status_text_color(self):
        (_, color) = ComponentStatusChoices.colors.get(self.status)
        return color

statuspage_app/statuspage/components/forms/bulk.py
from django import forms

from statuspage.forms import StatusPageModelBulkEditForm
from utilities.forms import StaticSelect, add_blank_choice, BulkEditNullBooleanSelect
from ..models import Component, ComponentGroup
from .. import choices

__all__ = (
    'ComponentGroupBulkEditForm',
    'ComponentBulkEditForm',
)


class ComponentBulkEditForm(StatusPageModelBulkEditForm):
    description = forms.CharField(
        max_length=255,
        required=False,
    )
    link = forms.URLField(
        max_length=255,
        required=False,
    )
    component_group = forms.ModelChoiceField(
        queryset=ComponentGroup.objects.all(),
        required=False,
        widget=StaticSelect(),
        label='Component Group',
    )
    show_historic_incidents = forms.NullBooleanField(
        required=False,
        widget=BulkEditNullBooleanSelect,
        label='Show historic Incidents',
    )
    visibility = forms.NullBooleanField(
        required=False,
        widget=BulkEditNullBooleanSelect,
        label='Visible',
    )
    status = forms.ChoiceField(
        choices=add_blank_choice(choices.ComponentStatusChoices),
        required=False,
        widget=StaticSelect(),
    )
    order = forms.IntegerField(
        required=False,
    )

    model = Component
    fieldsets = (
        ('Component', ('description', 'link', 'component_group', 'show_historic_incidents', 'visibility', 'status',
                       'order')),
    )
    nullable_fields = ('link', 'description', 'component_group')


class ComponentGroupBulkEditForm(StatusPageModelBulkEditForm):
    description = forms.CharField(
        max_length=255,
        required=False,
    )
    visibility = forms.NullBooleanField(
        required=False,
        widget=BulkEditNullBooleanSelect,
        label='Visible',
    )
    order = forms.IntegerField(
        required=False,
    )
    collapse = forms.ChoiceField(
        choices=add_blank_choice(choices.ComponentGroupCollapseChoices),
        required=False,
        widget=StaticSelect(),
    )

    model = ComponentGroup
    fieldsets = (
        ('Component', ('description', 'visibility', 'order', 'collapse')),
    )
    nullable_fields = ('link', 'description')

statuspage_app/statuspage/components/forms/filtersets.py
from django import forms

from components.models import Component, ComponentGroup
from components.choices import ComponentStatusChoices, ComponentGroupCollapseChoices
from utilities.forms import FilterForm, StaticSelect, add_blank_choice, \
    BOOLEAN_WITH_BLANK_CHOICES

__all__ = (
    'ComponentGroupFilterForm',
    'ComponentFilterForm',
)


class ComponentGroupFilterForm(FilterForm):
    model = ComponentGroup
    fieldsets = (
        (None, ('q',)),
        ('Component Group', ('name', 'description', 'visibility', 'order', 'collapse')),
    )
    name = forms.CharField(
        required=False,
    )
    description = forms.CharField(
        required=False,
    )
    visibility = forms.NullBooleanField(
        required=False,
        widget=StaticSelect(
            choices=BOOLEAN_WITH_BLANK_CHOICES,
        ),
    )
    order = forms.IntegerField(
        required=False,
    )
    collapse = forms.ChoiceField(
        required=False,
        choices=add_blank_choice(ComponentGroupCollapseChoices),
        widget=StaticSelect(),
    )


class ComponentFilterForm(FilterForm):
    model = Component
    fieldsets = (
        (None, ('q',)),
        ('Component', ('name', 'link', 'description', 'show_historic_incidents', 'visibility', 'status', 'order')),
    )
    name = forms.CharField(
        required=False,
    )
    link = forms.CharField(
        required=False,
    )
    description = forms.CharField(
        required=False,
    )
    show_historic_incidents = forms.NullBooleanField(
        required=False,
        widget=StaticSelect(
            choices=BOOLEAN_WITH_BLANK_CHOICES,
        ),
    )
    visibility = forms.NullBooleanField(
        required=False,
        widget=StaticSelect(
            choices=BOOLEAN_WITH_BLANK_CHOICES,
        ),
    )
    status = forms.ChoiceField(
        required=False,
        choices=add_blank_choice(ComponentStatusChoices),
        widget=StaticSelect(),
    )
    order = forms.IntegerField(
        required=False,
    )
    component_group = forms.ModelChoiceField(
        required=False,
        queryset=ComponentGroup.objects.all(),
        widget=StaticSelect(),
    )

statuspage_app/statuspage/components/api/views.py
from rest_framework.routers import APIRootView
from rest_framework.viewsets import ModelViewSet

from components.api import serializers
from components import filtersets
from components.models import Component, ComponentGroup


class ComponentsRootView(APIRootView):
    """
    Components API root view
    """
    def get_view_name(self):
        return 'Components'


class ComponentGroupViewSet(ModelViewSet):
    queryset = ComponentGroup.objects.all()
    serializer_class = serializers.ComponentGroupSerializer
    filterset_class = filtersets.ComponentGroupFilterSet


class ComponentViewSet(ModelViewSet):
    queryset = Component.objects.all()
    serializer_class = serializers.ComponentSerializer
    filterset_class = filtersets.ComponentFilterSet

statuspage_app/statuspage/components/views.py
from statuspage.views import generic
from statuspage.views.generic.mixins import ActionsMixin
from utilities.views import register_model_view
from .models import Component, ComponentGroup
from . import tables
from . import forms
from . import filtersets


@register_model_view(Component, 'list')
class ComponentListView(generic.ObjectListView):
    queryset = Component.objects.all()
    table = tables.ComponentTable
    filterset = filtersets.ComponentFilterSet
    filterset_form = forms.ComponentFilterForm


@register_model_view(Component)
class ComponentView(generic.ObjectView):
    queryset = Component.objects.all()


@register_model_view(Component, 'edit')
@register_model_view(Component, 'add')
class ComponentEditView(generic.ObjectEditView):
    queryset = Component.objects.all()
    form = forms.ComponentForm


@register_model_view(Component, 'delete')
class ComponentDeleteView(generic.ObjectDeleteView):
    queryset = Component.objects.all()


@register_model_view(Component, 'bulk_edit')
class ComponentBulkEditView(generic.BulkEditView):
    queryset = Component.objects.all()
    table = tables.ComponentTable
    form = forms.ComponentBulkEditForm


@register_model_view(Component, 'bulk_delete')
class ComponentBulkDeleteView(generic.BulkDeleteView):
    queryset = Component.objects.all()
    table = tables.ComponentTable


@register_model_view(ComponentGroup, 'list')
class ComponentGroupListView(generic.ObjectListView):
    queryset = ComponentGroup.objects.all()
    table = tables.ComponentGroupTable
    filterset = filtersets.ComponentGroupFilterSet
    filterset_form = forms.ComponentGroupFilterForm


@register_model_view(ComponentGroup)
class ComponentGroupView(generic.ObjectView, ActionsMixin):
    queryset = ComponentGroup.objects.all()

    def get_extra_context(self, request, instance):
        queryset = instance.components.all()

        actions = self.get_permitted_actions(request.user)
        has_bulk_actions = any([a.startswith('bulk_') for a in actions])

        table = tables.ComponentTable(queryset)
        if 'pk' in table.base_columns and has_bulk_actions:
            table.columns.show('pk')
        table.configure(request)

        return {
            'model': queryset.model,
            'table': table,
            'actions': actions,
        }


@register_model_view(ComponentGroup, 'edit')
@register_model_view(ComponentGroup, 'add')
class ComponentGroupEditView(generic.ObjectEditView):
    queryset = ComponentGroup.objects.all()
    form = forms.ComponentGroupForm


@register_model_view(ComponentGroup, 'delete')
class ComponentGroupDeleteView(generic.ObjectDeleteView):
    queryset = ComponentGroup.objects.all()


@register_model_view(ComponentGroup, 'bulk_edit')
class ComponentGroupBulkEditView(generic.BulkEditView):
    queryset = ComponentGroup.objects.all()
    table = tables.ComponentGroupTable
    form = forms.ComponentGroupBulkEditForm


@register_model_view(ComponentGroup, 'bulk_delete')
class ComponentGroupBulkDeleteView(generic.BulkDeleteView):
    queryset = ComponentGroup.objects.all()
    table = tables.ComponentGroupTable

statuspage_app/statuspage/templates/components/component.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}

{% block page_left %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Component</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Link</th>
            <td>{{ object.link|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Description</th>
            <td>{{ object.description|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Show Historic Incidents</th>
            <td>{% checkmark object.show_historic_incidents %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Visible</th>
            <td>{% checkmark object.visibility %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Status</th>
            <td>{% badge object.get_status_display bg_color=object.get_status_color %}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block page_right %}
  {% if object.component_group %}
    <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
      <div class="text-2xl">Component Group</div>
      <div class="px-4">
        <table class="text-left w-full">
          <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
            <tr>
              <th scope="row" class="pr-6 py-1">Name</th>
              <td>{{ object.component_group.name }}</td>
            </tr>
            <tr>
              <th scope="row" class="pr-6 py-1">Description</th>
              <td>{{ object.component_group.description|placeholder }}</td>
            </tr>
            <tr>
              <th scope="row" class="pr-6 py-1">Visible</th>
              <td>{% checkmark object.component_group.visibility %}</td>
            </tr>
            <tr>
              <th scope="row" class="pr-6 py-1">Collapse</th>
              <td>{{ object.component_group.get_collapse_display }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}
{% endblock %}

statuspage_app/statuspage/templates/components/componentgroup.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}

{% block page_left %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">Component Group</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Description</th>
            <td>{{ object.description|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Visible</th>
            <td>{% checkmark object.visibility %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Collapse</th>
            <td>{{ object.get_collapse_display }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block page_right %}{% endblock %}

{% block page_full %}
  <form method="post" class="form form-horizontal">
    {% csrf_token %}
    <input type="hidden" name="return_url" value="{% if return_url %}{{ return_url }}{% else %}{{ request.path }}{% if request.GET %}?{{ request.GET.urlencode }}{% endif %}{% endif %}" />

    <div id="object_list">
      {% include 'htmx/table.html' %}
    </div>

    {# Form buttons #}
    <div class="print:hidden bulk-buttons mt-4">
      <div class="bulk-button-group">
        {% block bulk_buttons %}
          {% if 'bulk_edit' in actions %}
            {% bulk_edit_button model query_params=request.GET %}
          {% endif %}
          {% if 'bulk_delete' in actions %}
            {% bulk_delete_button model query_params=request.GET %}
          {% endif %}
        {% endblock %}
      </div>
    </div>
  </form>
{% endblock %}