statuspage_app/statuspage/sp_external_status_providers/urls.py
from django.urls import path, include

from utilities.urls import get_model_urls
from . import views # noqa Required for registration

urlpatterns = [
    path('', include(get_model_urls('sp_external_status_providers', 'externalstatuspage'))),
    path('components/', include(get_model_urls('sp_external_status_providers', 'externalstatuscomponent'))),
]

statuspage_app/statuspage/statuspage/urls.py
from django.conf import settings
from django.views.static import serve

from extras.plugins.urls import plugin_patterns, plugin_api_patterns, plugin_admin_patterns
from .admin import admin_site
from django.urls import path, include, re_path
from statuspage.views import HomeView, DashboardHomeView, SubscriberVerifyView, SubscriberManageView, \
    SubscriberUnsubscribeView, SubscriberSubscribeView, SubscriberRequestManagementKeyView, \
    SubscriberManageWebhookListView, SubscriberManageWebhookCreateView, SubscriberManageWebhookDeleteView, \
    SubscriberManageWebhookEditView
from users.views import LoginView, LogoutView
from statuspage.api.views import APIRootView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

openapi_info = openapi.Info(
    title="Status-Page API",
    default_version='v1',
    description="API to access Status-Page",
    terms_of_service="https://github.com/status-page/status-page",
    license=openapi.License(name="Apache 2.0 License"),
)

schema_view = get_schema_view(
    openapi_info,
    validators=['flex', 'ssv'],
    public=True,
    permission_classes=()
)

_patterns = [
    # Base Views
    path('', HomeView.as_view(), name='home'),

    path('subscribers/subscribe', SubscriberSubscribeView.as_view(), name='subscriber_subscribe'),
    path('subscribers/reqeust-management-key', SubscriberRequestManagementKeyView.as_view(), name='subscriber_management_key'),
    path('subscribers/<str:management_key>/verify', SubscriberVerifyView.as_view(), name='subscriber_verify'),
    path('subscribers/<str:management_key>/manage', SubscriberManageView.as_view(), name='subscriber_manage'),
    path('subscribers/<str:management_key>/manage/webhooks', SubscriberManageWebhookListView.as_view(), name='subscriber_manage_webhook_list'),
    path('subscribers/<str:management_key>/manage/webhooks/create', SubscriberManageWebhookCreateView.as_view(), name='subscriber_manage_webhook_create'),
    path('subscribers/<str:management_key>/manage/webhooks/<int:webhook>/edit', SubscriberManageWebhookEditView.as_view(), name='subscriber_manage_webhook_edit'),
    path('subscribers/<str:management_key>/manage/webhooks/<int:webhook>/delete', SubscriberManageWebhookDeleteView.as_view(), name='subscriber_manage_webhook_delete'),
    path('subscribers/<str:management_key>/unsubscribe', SubscriberUnsubscribeView.as_view(), name='subscriber_unsubscribe'),

    path('dashboard/', DashboardHomeView.as_view(), name='dashboard'),
    path('dashboard/login/', LoginView.as_view(), name='login'),
    path('dashboard/logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path('dashboard/components/', include('components.urls')),
    path('dashboard/extras/', include('extras.urls')),
    path('dashboard/incidents/', include('incidents.urls')),
    path('dashboard/maintenances/', include('maintenances.urls')),
    path('dashboard/metrics/', include('metrics.urls')),
    path('dashboard/subscribers/', include('subscribers.urls')),
    path('dashboard/user/', include('users.urls')),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/components/', include('components.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/incidents/', include('incidents.api.urls')),
    path('api/maintenances/', include('maintenances.api.urls')),
    path('api/metrics/', include('metrics.api.urls')),
    path('api/subscribers/', include('subscribers.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=86400), name='api_docs'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=86400), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(cache_timeout=86400),
            name='schema_swagger'),

    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),

    # Admin
    path('admin/background-tasks/', include('django_rq.urls')),
    path('admin/plugins/', include(plugin_admin_patterns)),
    path('admin/', admin_site.urls),

    path('__reload__/', include('django_browser_reload.urls')),
]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

statuspage_app/statuspage/users/urls.py
from django.urls import path, include

from utilities.urls import get_model_urls
from . import views

app_name = 'users'
urlpatterns = [
    # User
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('preferences/', views.UserConfigView.as_view(), name='preferences'),
    path('password/', views.ChangePasswordView.as_view(), name='change_password'),

    # API Tokens
    path('api-tokens/', include(get_model_urls('users', 'token'))),

    # Two-Factor devices
    path('twofactor/', views.TwoFactorListView.as_view(), name='device_list'),
    path('twofactor/add/', views.TwoFactorEditView.as_view(), name='device_add'),
    path('twofactor/<int:pk>/backup-codes/', views.TwoFactorBackupCodesListView.as_view(), name='device_backup_codes'),
    path('twofactor/<int:pk>/qr-code/', views.TwoFactorQRCodeListView.as_view(), name='device_qr_code'),
    path('twofactor/<int:pk>/edit/', views.TwoFactorEditView.as_view(), name='device_edit'),
    path('twofactor/<int:pk>/delete/', views.TwoFactorDeleteView.as_view(), name='device_delete'),
]

statuspage_app/statuspage/sp_external_status_providers/forms/models.py
from statuspage.forms import StatusPageModelForm
from utilities.forms import StaticSelect
from ..models import ExternalStatusPage, ExternalStatusComponent

__all__ = (
    'ExternalStatusPageForm',
    'ExternalStatusComponentForm',
)


class ExternalStatusPageForm(StatusPageModelForm):
    fieldsets = (
        ('Page', (
            'domain', 'provider',
        )),
    )

    class Meta:
        model = ExternalStatusPage
        fields = (
            'domain', 'provider',
        )
        widgets = {
            'provider': StaticSelect(),
        }


class ExternalStatusComponentForm(StatusPageModelForm):
    fieldsets = (
        ('Page', (
            'component',
        )),
    )

    class Meta:
        model = ExternalStatusComponent
        fields = (
            'component',
        )
        widgets = {
            'component': StaticSelect(),
        }

statuspage_app/statuspage/sp_external_status_providers/models.py
from django.db import models
from django.urls import reverse

from components.choices import ComponentStatusChoices
from components.models import Component
from sp_external_status_providers.choices import ExternalStatusPageProviderChoices
from sp_external_status_providers.providers.atlassian import AtlassianProvider
from statuspage.models import StatusPageModel


class ExternalStatusPage(StatusPageModel):
    domain = models.CharField(
        max_length=255,
    )
    provider = models.CharField(
        max_length=255,
        choices=ExternalStatusPageProviderChoices,
    )
    create_incidents = models.BooleanField(
        default=False,
    )
    create_maintenances = models.BooleanField(
        default=False,
    )

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.domain}'

    def get_absolute_url(self):
        return reverse('plugins:sp_external_status_providers:externalstatuspage', args=[self.pk])

    @property
    def provider_class(self):
        match self.provider:
            case ExternalStatusPageProviderChoices.ATLASSIAN_STATUSPAGE:
                return AtlassianProvider


class ExternalStatusComponent(StatusPageModel):
    page_object_id = models.CharField(
        max_length=255,
    )
    name = models.CharField(
        max_length=255,
    )
    external_page = models.ForeignKey(
        to=ExternalStatusPage,
        on_delete=models.CASCADE,
        related_name='components',
    )
    component = models.ForeignKey(
        to=Component,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    group_name = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('plugins:sp_external_status_providers:externalstatuscomponent', args=[self.pk])

    @classmethod
    def status(cls, status_name):
        match status_name:
            case 'operational':
                return ComponentStatusChoices.OPERATIONAL
            case 'degraded_performance':
                return ComponentStatusChoices.DEGRADED_PERFORMANCE
            case 'partial_outage':
                return ComponentStatusChoices.PARTIAL_OUTAGE
            case 'major_outage':
                return ComponentStatusChoices.MAJOR_OUTAGE
            case 'under_maintenance':
                return ComponentStatusChoices.MAINTENANCE
            case _:
                return ComponentStatusChoices.UNKNOWN

    @classmethod
    def by_object_id(cls, component_id):
        try:
            return cls.objects.get(page_object_id=component_id)
        except:
            return None

statuspage_app/statuspage/sp_external_status_providers/forms/bulk.py
from django import forms

from components.models import Component
from statuspage.forms import StatusPageModelBulkEditForm
from utilities.forms import StaticSelect, BulkEditNullBooleanSelect
from ..choices import ExternalStatusPageProviderChoices
from ..models import ExternalStatusPage

__all__ = (
    'ExternalStatusPageBulkEditForm',
    'ExternalStatusComponentBulkEditForm',
)


class ExternalStatusPageBulkEditForm(StatusPageModelBulkEditForm):
    provider = forms.ChoiceField(
        choices=ExternalStatusPageProviderChoices,
        required=False,
        widget=StaticSelect(),
    )
    create_incidents = forms.NullBooleanField(
        required=False,
        widget=BulkEditNullBooleanSelect,
    )
    create_maintenances = forms.NullBooleanField(
        required=False,
        widget=BulkEditNullBooleanSelect,
    )

    model = ExternalStatusPage
    fieldsets = (
        ('Page', ('provider', 'create_incidents', 'create_maintenances')),
    )
    nullable_fields = ()


class ExternalStatusComponentBulkEditForm(StatusPageModelBulkEditForm):
    component = forms.ModelChoiceField(
        queryset=Component.objects.all(),
        required=False,
        widget=StaticSelect(),
    )

    model = ExternalStatusPage
    fieldsets = (
        ('Page', ('component',)),
    )
    nullable_fields = ('component',)

statuspage_app/statuspage/sp_external_status_providers/forms/filtersets.py
from django import forms

from components.models import Component
from ..choices import ExternalStatusPageProviderChoices
from ..models import ExternalStatusPage, ExternalStatusComponent
from utilities.forms import FilterForm, StaticSelect, add_blank_choice, \
    BOOLEAN_WITH_BLANK_CHOICES

__all__ = (
    'ExternalStatusPageFilterForm',
    'ExternalStatusComponentFilterForm',
)


class ExternalStatusPageFilterForm(FilterForm):
    model = ExternalStatusPage
    fieldsets = (
        (None, ('q',)),
        ('Page', ('provider', 'create_incidents', 'create_maintenances')),
    )
    provider = forms.ChoiceField(
        required=False,
        choices=add_blank_choice(ExternalStatusPageProviderChoices),
        widget=StaticSelect(),
    )
    create_incidents = forms.NullBooleanField(
        required=False,
        widget=StaticSelect(
            choices=BOOLEAN_WITH_BLANK_CHOICES,
        ),
    )
    create_maintenances = forms.NullBooleanField(
        required=False,
        widget=StaticSelect(
            choices=BOOLEAN_WITH_BLANK_CHOICES,
        ),
    )


class ExternalStatusComponentFilterForm(FilterForm):
    model = ExternalStatusComponent
    fieldsets = (
        (None, ('q',)),
        ('Component', ('external_page', 'component')),
    )
    external_page = forms.ModelChoiceField(
        queryset=ExternalStatusPage.objects.all(),
        widget=StaticSelect(),
    )
    component = forms.ModelChoiceField(
        queryset=Component.objects.all(),
        widget=StaticSelect(),
    )

statuspage_app/statuspage/sp_external_status_providers/views.py
from statuspage.views import generic
from statuspage.views.generic.mixins import ActionsMixin
from utilities.views import register_model_view
from .models import ExternalStatusPage, ExternalStatusComponent
from . import tables
from . import forms
from . import filtersets


@register_model_view(ExternalStatusPage, 'list')
class ExternalStatusPageListView(generic.ObjectListView):
    queryset = ExternalStatusPage.objects.all()
    table = tables.ExternalStatusPageTable
    filterset = filtersets.ExternalStatusPageFilterSet
    filterset_form = forms.ExternalStatusPageFilterForm


@register_model_view(ExternalStatusPage)
class ExternalStatusPageView(generic.ObjectView, ActionsMixin):
    queryset = ExternalStatusPage.objects.all()

    def get_extra_context(self, request, instance):
        queryset = instance.components.all()

        actions = self.get_permitted_actions(request.user)
        has_bulk_actions = any([a.startswith('bulk_') for a in actions])

        table = tables.ExternalStatusComponentTable(queryset)
        if 'pk' in table.base_columns and has_bulk_actions:
            table.columns.show('pk')
        table.configure(request)

        return {
            'model': queryset.model,
            'table': table,
            'actions': actions,
        }


@register_model_view(ExternalStatusPage, 'edit')
@register_model_view(ExternalStatusPage, 'add')
class ExternalStatusPageEditView(generic.ObjectEditView):
    queryset = ExternalStatusPage.objects.all()
    form = forms.ExternalStatusPageForm


@register_model_view(ExternalStatusPage, 'delete')
class ExternalStatusPageDeleteView(generic.ObjectDeleteView):
    queryset = ExternalStatusPage.objects.all()


@register_model_view(ExternalStatusPage, 'bulk_edit')
class ExternalStatusPageBulkEditView(generic.BulkEditView):
    queryset = ExternalStatusPage.objects.all()
    table = tables.ExternalStatusPageTable
    form = forms.ExternalStatusPageBulkEditForm


@register_model_view(ExternalStatusPage, 'bulk_delete')
class ExternalStatusPageBulkDeleteView(generic.BulkDeleteView):
    queryset = ExternalStatusPage.objects.all()
    table = tables.ExternalStatusPageTable


@register_model_view(ExternalStatusComponent, 'list')
class ExternalStatusComponentListView(generic.ObjectListView):
    queryset = ExternalStatusComponent.objects.all()
    table = tables.ExternalStatusComponentTable
    filterset = filtersets.ExternalStatusComponentFilterSet
    filterset_form = forms.ExternalStatusComponentFilterForm


@register_model_view(ExternalStatusComponent)
class ExternalStatusComponentView(generic.ObjectView):
    queryset = ExternalStatusComponent.objects.all()


@register_model_view(ExternalStatusComponent, 'edit')
@register_model_view(ExternalStatusComponent, 'add')
class ExternalStatusComponentEditView(generic.ObjectEditView):
    queryset = ExternalStatusComponent.objects.all()
    form = forms.ExternalStatusComponentForm


@register_model_view(ExternalStatusComponent, 'delete')
class ExternalStatusComponentDeleteView(generic.ObjectDeleteView):
    queryset = ExternalStatusComponent.objects.all()


@register_model_view(ExternalStatusComponent, 'bulk_edit')
class ExternalStatusComponentBulkEditView(generic.BulkEditView):
    queryset = ExternalStatusComponent.objects.all()
    table = tables.ExternalStatusComponentTable
    form = forms.ExternalStatusComponentBulkEditForm


@register_model_view(ExternalStatusComponent, 'bulk_delete')
class ExternalStatusComponentBulkDeleteView(generic.BulkDeleteView):
    queryset = ExternalStatusComponent.objects.all()
    table = tables.ExternalStatusComponentTable

statuspage_app/statuspage/sp_external_status_providers/templates/sp_external_status_providers/externalstatuscomponent.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}

{% block page_left %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">External Status Component</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Page Object Id</th>
            <td>{{ object.page_object_id }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Component</th>
            <td>{{ object.component|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Group Name</th>
            <td>{{ object.group_name|placeholder }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block page_right %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">External Status Page</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">Domain</th>
            <td>{{ object.external_page|linkify }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Provider</th>
            <td>{{ object.external_page.get_provider_display }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Create Incidents</th>
            <td>{% checkmark object.external_page.create_incidents %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Create Maintenances</th>
            <td>{% checkmark object.external_page.create_maintenances %}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

statuspage_app/statuspage/sp_external_status_providers/templates/sp_external_status_providers/externalstatuspage.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}

{% block page_left %}
  <div class="grow bg-zinc-100 dark:bg-zinc-800 p-2 space-y-2 ring-1 ring-zinc-500 rounded-md shadow-lg">
    <div class="text-2xl">External Status Page</div>
    <div class="px-4">
      <table class="text-left w-full">
        <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
          <tr>
            <th scope="row" class="pr-6 py-1">Domain</th>
            <td>{{ object.domain }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Provider</th>
            <td>{{ object.get_provider_display }}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Create Incidents</th>
            <td>{% checkmark object.create_incidents %}</td>
          </tr>
          <tr>
            <th scope="row" class="pr-6 py-1">Create Maintenances</th>
            <td>{% checkmark object.create_maintenances %}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block page_full %}
  <form method="post" class="form form-horizontal">
    {% csrf_token %}
    <input type="hidden" name="return_url" value="{% if return_url %}{{ return_url }}{% else %}{{ request.path }}{% if request.GET %}?{{ request.GET.urlencode }}{% endif %}{% endif %}" />

    <div id="object_list">
      {% include 'htmx/table.html' %}
    </div>

    {# Form buttons #}
    <div class="print:hidden bulk-buttons mt-4">
      <div class="bulk-button-group">
        {% block bulk_buttons %}
          {% if 'bulk_edit' in actions %}
            {% bulk_edit_button model query_params=request.GET %}
          {% endif %}
          {% if 'bulk_delete' in actions %}
            {% bulk_delete_button model query_params=request.GET %}
          {% endif %}
        {% endblock %}
      </div>
    </div>
  </form>
{% endblock %}